INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'random_translation', 'randaugment', 'normalize']

DATASET:
  NAME: 'Office31'

MODEL:
  BACKBONE:
    NAME: 'resnet50'#'resnet18'
    PRETRAINED: True
