INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip','colorjitter','randomgrayscale', 'normalize']
  #TRANSFORMS: ['random_resized_crop','colorjitter','randomgrayscale', 'normalize']
  #TRANSFORMS: ['randaugment', 'normalize']

DATASET:
  NAME: 'VLCS'

MODEL:
  BACKBONE:
    NAME: 'resnet18'
    PRETRAINED: True

TEST:
  PER_CLASS_RESULT: True

